swagger: "2.0"
info:
    title: test Title
    description: Teqnological asia api
    termsOfService: Golang team
    contact:
        email: contact@teqnological.asia
    license:
        name: Copy right @ 2023 teqnological
    version: 1.1.1
schemes:
    - http
    - https
consumes:
    - application/json
host: localhost
basePath: /api
paths:
    /api/user/{userID}/info:
        get:
            summary: get user information
            tags:
                - Account
            operationId: GetUserInfo
            parameters:
                - in: path
                  name: userID
                  type: string
                  required: true
            responses:
                "200":
                    description: OK
                    schema:
                        type: object
                        properties:
                            age:
                                type: string
                                example: "23"
                            is_handsome:
                                example: false
                            username:
                                type: string
                                example: quocbang
                "400":
                    description: Bad Request
                    schema:
                        type: object
                        properties:
                            Code:
                                type: integer
                                example: 10010
                            Details:
                                type: string
                                example: missing username
    /api/user/{userID}/upload:
        post:
            summary: upload user images
            tags:
                - Account
            operationId: UploadUserImage
            parameters:
                - in: path
                  name: userID
                  type: string
                  required: true
                - in: formData
                  name: file
                  type: file
            responses:
                "200":
                    description: OK
                    schema:
                        type: object
                        properties:
                            age:
                                type: string
                                example: "23"
                            is_handsome:
                                example: false
                            username:
                                type: string
                                example: quocbang
                "400":
                    description: Bad Request
                    schema:
                        type: object
                        properties:
                            Code:
                                type: integer
                                example: 10010
                            Details:
                                type: string
                                example: missing username
            consumes:
                - multipart/form-data
    /api/user/login:
        post:
            summary: login to server
            tags:
                - Account
            operationId: Login
            parameters:
                - in: body
                  name: body
                  required: true
                  schema:
                    $ref: '#/definitions/LoginRequest'
            responses:
                "200":
                    description: OK
                    schema:
                        type: object
                        properties:
                            created_at:
                                type: string
                                example: string
                            created_by:
                                type: integer
                                example: 0
                            id:
                                type: integer
                                example: 0
                            name:
                                type: string
                                example: string
                            updated_at:
                                type: string
                                example: string
                            updated_by:
                                type: integer
                                example: 0
                "400":
                    description: Bad Request
                    schema:
                        type: object
                        properties:
                            Code:
                                type: integer
                                example: 10010
                            Details:
                                type: string
                                example: missing id
definitions:
    LoginRequest:
        type: object
        properties:
            password:
                type: string
                example: test
            permission:
                type: array
                items:
                    type: string
                    example:
                        - abc
                        - djsgdj
                        - skdhdkh
            tests:
                type: array
                items:
                    type: object
                    properties:
                        password:
                            type: string
                            example: test password 2
                        username:
                            type: string
                            example: test 2
            user_info:
                type: object
                properties:
                    age:
                        type: integer
                        example: 23
                    full_name:
                        type: string
                        example: thong quoc bang
                    position:
                        type: array
                        items:
                            type: integer
                            example:
                                - 1
                                - 2
                                - 3
                                - 4
                                - 5
            username:
                type: string
                example: test
