swagger: "2.0"
info:
    title: test Title
    description: Teqnological asia api
    termsOfService: Golang team
    contact:
        email: contact@teqnological.asia
    license:
        name: Copy right @ 2023 teqnological
    version: 1.1.1
schemes:
    - http
    - https
consumes:
    - application/json
host: localhost
basePath: /api
paths:
    /user/info/{id}:
        get:
            summary: get user info
            description: get user
            tags:
                - Account
            operationId: ListUserInfo
            parameters:
                - in: path
                  name: id
                  type: string
                  required: true
                - in: body
                  name: body
                  required: true
                  schema:
                    properties:
                        Data:
                            type: object
            responses:
                "200":
                    description: OK
                    schema:
                        properties:
                            Data:
                                type: array
                                items:
                                    properties:
                                        Age:
                                            type: integer
                                            description: user age
                                        Username:
                                            type: string
                                            description: name of the user
    /user/login:
        post:
            summary: login
            description: login to server
            tags:
                - Account
            operationId: Login
            parameters:
                - in: body
                  name: body
                  required: true
                  schema:
                    $ref: '#/definitions/LoginRequest'
            responses:
                "200":
                    description: OK
                    schema:
                        $ref: '#/definitions/LoginResponse'
definitions:
    LoginRequest:
        type: object
        default: '{"username": "", "password": ""}'
    LoginResponse:
        type: object
        default: '{"access_token": "abc", "refresh_token": "abc"}'
